
;; A standalone Emacs theme based on NanoTech's jellybeans.vim 1.7
;; (https://github.com/nanotech/jellybeans.vim), originally released under MIT.
;; This port maps the Vim highlight groups and palette to Emacs faces.

;;; Code:

(deftheme jellybeans-vim
  "An Emacs port of neovim colorscheme.")

(let* ((class '((class color) (min-colors 89)))
       (bg          "#151515")
       (bg-alt      "#1c1c1c")
       (fg          "#e8e8d3")
       (fg-alt      "#c7c7c7")
       (comment     "#888888")
       (dim         "#606060")
       (line-number "#605958")
       (cursor-line "#1c1c1c")
       (selection   "#404040")
       (match-bg    "#556779")
       (cursor      "#b0d0f0")
       (constant    "#cf6a4c")
       (special     "#799d6a")
       (delimiter   "#668799")
       (string      "#99ad6a")
       (string-delim "#556633")
       (identifier  "#c6b6ee")
       (structure   "#8fbfdc")
       (function    "#fad07a")
       (statement   "#8197bf")
       (type        "#ffb964")
       (storage     "#c59f6f")
       (directory   "#dad085")
       (title       "#70b950")
       (question    "#65c254")
       (pink        "#f0a0c0")
       (pink-bg     "#302028")
       (error-bg    "#902020")
       (fold-fg     "#a0a8b0")
       (fold-bg     "#384048")
       (border      "#403c41")
       (popup-bg    "#606060")
       (popup-sel-fg "#101010")
       (popup-sel-bg "#eeeeee")
       (diff-add-fg "#d2ebbe")
       (diff-add-bg "#437019")
       (diff-del-fg "#40000a")
       (diff-del-bg "#700009")
       (diff-chg-bg "#2b5b77")
       (ruby-class  "#447799")
       (ruby-ident  "#c6b6fe")
       (ruby-symbol "#7697d6")
       (ruby-control "#7597c6")
       (regexp-delim "#540063")
       (regexp      "#dd0093")
       (regexp-special "#a40073")
       (predefined  "#de5577"))

  (custom-theme-set-faces
   'jellybeans-vim

   ;; Core UI
   `(default ((,class (:background ,bg :foreground ,fg))))
   `(cursor ((,class (:background ,cursor :foreground ,bg))))
   `(fringe ((,class (:background ,bg :foreground ,dim))))
   `(region ((,class (:background ,selection))))
   `(secondary-selection ((,class (:background ,border))))
   `(highlight ((,class (:background ,bg-alt))))
   `(hl-line ((,class (:background ,cursor-line))))
   `(vertical-border ((,class (:foreground "#777777"))))
   `(window-divider ((,class (:foreground ,border))))
   `(window-divider-first-pixel ((,class (:foreground ,border))))
   `(window-divider-last-pixel ((,class (:foreground ,border))))
   `(minibuffer-prompt ((,class (:foreground ,structure :weight bold))))
   `(link ((,class (:foreground ,structure :underline t))))
   `(link-visited ((,class (:foreground ,identifier :underline t))))
   `(shadow ((,class (:foreground ,dim))))
   `(success ((,class (:foreground ,question))))
   `(warning ((,class (:foreground ,function))))
   `(error ((,class (:foreground ,fg :background ,error-bg :weight bold))))
   `(match ((,class (:foreground "#ffffff" :background ,match-bg :weight bold))))
   `(lazy-highlight ((,class (:foreground ,pink :background ,pink-bg))))
   `(isearch ((,class (:foreground ,pink :background ,pink-bg :underline t))))
   `(isearch-fail ((,class (:foreground ,fg :background ,error-bg))))
   `(trailing-whitespace ((,class (:background ,error-bg))))
   `(escape-glyph ((,class (:foreground ,special))))
   `(homoglyph ((,class (:foreground ,constant))))

   ;; Line numbers / columns
   `(line-number ((,class (:foreground ,line-number :background ,bg))))
   `(line-number-current-line ((,class (:foreground "#ccc5c4" :background ,bg))))
   `(fill-column-indicator ((,class (:foreground "#000000"))))

   ;; Mode line (Vim StatusLine / StatusLineNC)
   `(mode-line ((,class (:foreground "#cccccc" :background "#333344" :slant italic :box nil))))
   `(mode-line-inactive ((,class (:foreground "#7f7f7f" :background ,border :slant italic :box nil))))
   `(mode-line-buffer-id ((,class (:weight bold))))
   `(header-line ((,class (:foreground ,fg :background ,border :box nil))))

   ;; Tabs
   `(tab-bar ((,class (:foreground "#9098a0" :background ,bg))))
   `(tab-bar-tab ((,class (:foreground "#000000" :background "#f0f0f0" :weight bold :slant italic :box nil))))
   `(tab-bar-tab-inactive ((,class (:foreground "#000000" :background "#b0b8c0" :slant italic :box nil))))
   `(tab-line ((,class (:foreground "#9098a0" :background ,bg))))
   `(tab-line-tab ((,class (:foreground "#000000" :background "#f0f0f0" :weight bold :slant italic :box nil))))
   `(tab-line-tab-current ((,class (:foreground "#000000" :background "#f0f0f0" :weight bold :slant italic :box nil))))
   `(tab-line-tab-inactive ((,class (:foreground "#000000" :background "#b0b8c0" :slant italic :box nil))))

   ;; Completion/popups (Vim Pmenu/PmenuSel)
   `(completions-common-part ((,class (:foreground ,function :weight bold))))
   `(completions-first-difference ((,class (:foreground ,statement))))
   `(tooltip ((,class (:foreground "#ffffff" :background ,popup-bg))))

   ;; Font Lock: direct translation of the major Vim syntax groups
   `(font-lock-comment-face ((,class (:foreground ,comment :slant italic))))
   `(font-lock-comment-delimiter-face ((,class (:foreground ,comment :slant italic))))
   `(font-lock-doc-face ((,class (:foreground ,comment :slant italic))))
   `(font-lock-doc-markup-face ((,class (:foreground ,special))))
   `(font-lock-string-face ((,class (:foreground ,string))))
   `(font-lock-constant-face ((,class (:foreground ,constant))))
   `(font-lock-number-face ((,class (:foreground ,constant))))
   `(font-lock-variable-name-face ((,class (:foreground ,identifier))))
   `(font-lock-variable-use-face ((,class (:foreground ,identifier))))
   `(font-lock-function-name-face ((,class (:foreground ,function))))
   `(font-lock-function-call-face ((,class (:foreground ,function))))
   `(font-lock-keyword-face ((,class (:foreground ,statement))))
   `(font-lock-type-face ((,class (:foreground ,type))))
   `(font-lock-builtin-face ((,class (:foreground ,structure))))
   `(font-lock-preprocessor-face ((,class (:foreground ,structure))))
   `(font-lock-negation-char-face ((,class (:foreground ,structure))))
   `(font-lock-warning-face ((,class (:foreground ,fg :background ,error-bg :weight bold))))
   `(font-lock-regexp-grouping-backslash ((,class (:foreground ,regexp-delim))))
   `(font-lock-regexp-grouping-construct ((,class (:foreground ,regexp))))
   `(font-lock-escape-face ((,class (:foreground ,special))))
   `(font-lock-operator-face ((,class (:foreground ,structure))))
   `(font-lock-punctuation-face ((,class (:foreground ,delimiter))))
   `(font-lock-delimiter-face ((,class (:foreground ,delimiter))))
   `(font-lock-bracket-face ((,class (:foreground ,delimiter))))
   `(font-lock-misc-punctuation-face ((,class (:foreground ,delimiter))))

   ;; Generic faces often used by major modes
   `(fixed-pitch ((,class (:foreground ,fg))))
   `(fixed-pitch-serif ((,class (:foreground ,fg))))
   `(variable-pitch ((,class (:foreground ,fg))))
   `(bold ((,class (:weight bold))))
   `(italic ((,class (:slant italic))))

   ;; Parentheses / show-paren
   `(show-paren-match ((,class (:foreground "#ffffff" :background ,match-bg :weight bold))))
   `(show-paren-mismatch ((,class (:foreground ,fg :background ,error-bg :weight bold))))

   ;; Buttons / widgets
   `(button ((,class (:foreground ,structure :underline t))))
   `(widget-field ((,class (:background ,bg-alt))))
   `(widget-button ((,class (:foreground ,function :weight bold))))
   `(custom-button ((,class (:foreground "#000000" :background "#dddddd" :box nil))))

   ;; Folds / outline
   `(outline-1 ((,class (:foreground ,title :weight bold))))
   `(outline-2 ((,class (:foreground ,function :weight bold))))
   `(outline-3 ((,class (:foreground ,structure :weight bold))))
   `(outline-4 ((,class (:foreground ,identifier :weight bold))))
   `(outline-5 ((,class (:foreground ,type :weight bold))))
   `(outline-6 ((,class (:foreground ,special :weight bold))))
   `(outline-7 ((,class (:foreground ,constant :weight bold))))
   `(outline-8 ((,class (:foreground ,statement :weight bold))))

   ;; Org
   `(org-document-title ((,class (:foreground ,title :weight bold :height 1.2))))
   `(org-document-info ((,class (:foreground ,structure))))
   `(org-level-1 ((,class (:foreground ,title :weight bold))))
   `(org-level-2 ((,class (:foreground ,function :weight bold))))
   `(org-level-3 ((,class (:foreground ,structure :weight bold))))
   `(org-level-4 ((,class (:foreground ,identifier :weight bold))))
   `(org-level-5 ((,class (:foreground ,type :weight bold))))
   `(org-code ((,class (:foreground ,string))))
   `(org-verbatim ((,class (:foreground ,constant))))
   `(org-block ((,class (:foreground ,fg-alt :background ,bg-alt))))
   `(org-block-begin-line ((,class (:foreground ,dim :background ,bg-alt))))
   `(org-block-end-line ((,class (:foreground ,dim :background ,bg-alt))))
   `(org-link ((,class (:foreground ,structure :underline t))))
   `(org-todo ((,class (:foreground ,fg-alt :weight bold))))
   `(org-done ((,class (:foreground ,special :weight bold))))
   `(org-date ((,class (:foreground ,identifier :underline t))))
   `(org-special-keyword ((,class (:foreground ,statement))))
   `(org-meta-line ((,class (:foreground ,comment :slant italic))))

   ;; Markdown
   `(markdown-header-face-1 ((,class (:foreground ,title :weight bold))))
   `(markdown-header-face-2 ((,class (:foreground ,function :weight bold))))
   `(markdown-header-face-3 ((,class (:foreground ,structure :weight bold))))
   `(markdown-header-face-4 ((,class (:foreground ,identifier :weight bold))))
   `(markdown-code-face ((,class (:foreground ,string :background ,bg-alt))))
   `(markdown-inline-code-face ((,class (:foreground ,string))))
   `(markdown-link-face ((,class (:foreground ,structure))))
   `(markdown-url-face ((,class (:foreground ,identifier :underline t))))

   ;; Diff / ediff
   `(diff-added ((,class (:foreground ,diff-add-fg :background ,diff-add-bg))))
   `(diff-removed ((,class (:foreground ,diff-del-fg :background ,diff-del-bg))))
   `(diff-changed ((,class (:foreground ,fg :background ,diff-chg-bg))))
   `(diff-refine-added ((,class (:foreground ,bg :background ,diff-add-fg :weight bold))))
   `(diff-refine-removed ((,class (:foreground ,fg :background ,diff-del-bg :weight bold))))
   `(diff-refine-changed ((,class (:foreground ,structure :background "#000000" :weight bold))))
   `(diff-header ((,class (:foreground ,fg :background ,border))))
   `(diff-file-header ((,class (:foreground ,function :background ,border :weight bold))))
   `(ediff-current-diff-A ((,class (:background ,diff-del-bg))))
   `(ediff-current-diff-B ((,class (:background ,diff-add-bg))))
   `(ediff-current-diff-C ((,class (:background ,diff-chg-bg))))

   ;; Magit
   `(magit-section-heading ((,class (:foreground ,function :weight bold))))
   `(magit-section-highlight ((,class (:background ,bg-alt))))
   `(magit-branch-local ((,class (:foreground ,structure))))
   `(magit-branch-remote ((,class (:foreground ,special))))
   `(magit-hash ((,class (:foreground ,dim))))
   `(magit-diff-added ((,class (:foreground ,diff-add-fg :background ,diff-add-bg))))
   `(magit-diff-added-highlight ((,class (:foreground ,diff-add-fg :background ,diff-add-bg :weight bold))))
   `(magit-diff-removed ((,class (:foreground ,diff-del-fg :background ,diff-del-bg))))
   `(magit-diff-removed-highlight ((,class (:foreground ,fg :background ,diff-del-bg :weight bold))))
   `(magit-diff-context ((,class (:foreground ,fg-alt :background ,bg))))
   `(magit-diff-context-highlight ((,class (:foreground ,fg :background ,bg-alt))))
   `(magit-diff-file-heading ((,class (:foreground ,fg :weight bold))))
   `(magit-diff-file-heading-highlight ((,class (:foreground ,function :background ,bg-alt :weight bold))))
   `(magit-diff-hunk-heading ((,class (:foreground ,fg :background ,border))))
   `(magit-diff-hunk-heading-highlight ((,class (:foreground ,fg :background ,match-bg))))

   ;; Dired / directories
   `(dired-directory ((,class (:foreground ,directory :weight bold))))
   `(dired-symlink ((,class (:foreground ,structure))))
   `(dired-marked ((,class (:foreground ,function :weight bold))))
   `(dired-flagged ((,class (:foreground ,constant :weight bold))))
   `(dired-header ((,class (:foreground ,title :weight bold))))

   ;; Compilation / grep
   `(compilation-info ((,class (:foreground ,special))))
   `(compilation-warning ((,class (:foreground ,function))))
   `(compilation-error ((,class (:foreground ,constant :weight bold))))
   `(compilation-line-number ((,class (:foreground ,structure))))
   `(grep-hit-face ((,class (:foreground ,special))))
   `(grep-match-face ((,class (:foreground ,pink :background ,pink-bg))))

   ;; Flycheck / Flymake diagnostics
   `(flycheck-error ((,class (:underline (:style wave :color ,constant)))))
   `(flycheck-warning ((,class (:underline (:style wave :color ,function)))))
   `(flycheck-info ((,class (:underline (:style wave :color ,structure)))))
   `(flymake-error ((,class (:underline (:style wave :color ,constant)))))
   `(flymake-warning ((,class (:underline (:style wave :color ,function)))))
   `(flymake-note ((,class (:underline (:style wave :color ,structure)))))

   ;; Spell checking, based on Vim Spell* groups
   `(flyspell-incorrect ((,class (:underline (:style wave :color ,error-bg)))))
   `(flyspell-duplicate ((,class (:underline (:style wave :color "#2d7067")))))

   ;; Company / Corfu / Vertico / Consult
   `(company-tooltip ((,class (:foreground "#cccccc" :background "#1c1c1c",popup-bg))))
   `(company-tooltip-selection ((,class (:foreground "#cccccc" :background "#262626"))))
   `(company-tooltip-common ((,class (:foreground ,function :weight bold))))
   `(company-scrollbar-bg ((,class (:background ,border))))
   `(company-scrollbar-fg ((,class (:background ,dim))))
   `(corfu-default ((,class (:foreground "#cccccc" :background "#1c1c1c",popup-bg))))
   `(corfu-current ((,class (:foreground "#cccccc" :background "#262626"))))
   `(corfu-border ((,class (:background ,border))))
   `(vertico-current ((,class (:foreground "#cccccc" :background "#1c1c1c"))))
   `(consult-highlight-match ((,class (:foreground ,function :weight bold))))
   ;; Which-key
   `(which-key-key-face ((,class (:foreground ,function))))
   `(which-key-command-description-face ((,class (:foreground ,fg))))
   `(which-key-group-description-face ((,class (:foreground ,structure))))
   `(which-key-local-map-description-face ((,class (:foreground ,special))))

   ;; Ivy / Helm (if used)
   `(ivy-current-match ((,class (:foreground ,popup-sel-fg :background ,popup-sel-bg))))
   `(ivy-minibuffer-match-face-1 ((,class (:foreground ,fg))))
   `(ivy-minibuffer-match-face-2 ((,class (:foreground ,function :weight bold))))
   `(ivy-minibuffer-match-face-3 ((,class (:foreground ,structure :weight bold))))
   `(ivy-minibuffer-match-face-4 ((,class (:foreground ,identifier :weight bold))))
   `(helm-selection ((,class (:foreground ,popup-sel-fg :background ,popup-sel-bg))))
   `(helm-match ((,class (:foreground ,function :weight bold))))

   ;; Doom dashboard / modeline
   `(doom-dashboard-banner ((,class (:foreground ,title :weight bold))))
   `(doom-dashboard-menu-title ((,class (:foreground ,function :weight bold))))
   `(doom-dashboard-menu-desc ((,class (:foreground ,fg))))
   `(doom-dashboard-footer ((,class (:foreground ,comment :slant italic))))
   `(doom-modeline-buffer-file ((,class (:foreground ,fg :weight bold))))
   `(doom-modeline-buffer-modified ((,class (:foreground ,constant :weight bold))))
   `(doom-modeline-project-dir ((,class (:foreground ,structure))))
   `(doom-modeline-project-root-dir ((,class (:foreground ,directory :weight bold))))

   ;; Neotree / Treemacs
   `(neo-root-dir-face ((,class (:foreground ,title :weight bold))))
   `(neo-dir-link-face ((,class (:foreground ,directory))))
   `(neo-file-link-face ((,class (:foreground ,fg))))
   `(neo-expand-btn-face ((,class (:foreground ,dim))))
   `(treemacs-root-face ((,class (:foreground ,title :weight bold))))
   `(treemacs-directory-face ((,class (:foreground ,directory))))
   `(treemacs-file-face ((,class (:foreground ,fg))))
   `(treemacs-git-added-face ((,class (:foreground ,special))))
   `(treemacs-git-modified-face ((,class (:foreground ,function))))
   `(treemacs-git-conflict-face ((,class (:foreground ,constant))))
   `(treemacs-git-untracked-face ((,class (:foreground ,identifier))))

   ;; Centaur tabs
   `(centaur-tabs-default ((,class (:foreground "#9098a0" :background ,bg))))
   `(centaur-tabs-selected ((,class (:foreground "#000000" :background "#f0f0f0" :weight bold))))
   `(centaur-tabs-unselected ((,class (:foreground "#000000" :background "#b0b8c0"))))
   `(centaur-tabs-selected-modified ((,class (:foreground ,constant :background "#f0f0f0" :weight bold))))
   `(centaur-tabs-unselected-modified ((,class (:foreground ,constant :background "#b0b8c0"))))

   ;; LSP UI
   `(lsp-face-highlight-textual ((,class (:background ,bg-alt))))
   `(lsp-face-highlight-read ((,class (:background ,bg-alt))))
   `(lsp-face-highlight-write ((,class (:background ,selection))))
   `(lsp-ui-doc-background ((,class (:background ,bg-alt))))
   `(lsp-ui-peek-header ((,class (:foreground ,fg :background ,border :weight bold))))
   `(lsp-ui-peek-selection ((,class (:foreground ,popup-sel-fg :background ,popup-sel-bg))))

   ;; Rainbow delimiters (kept within Jellybeans palette)
   `(rainbow-delimiters-depth-1-face ((,class (:foreground ,delimiter))))
   `(rainbow-delimiters-depth-2-face ((,class (:foreground ,structure))))
   `(rainbow-delimiters-depth-3-face ((,class (:foreground ,identifier))))
   `(rainbow-delimiters-depth-4-face ((,class (:foreground ,function))))
   `(rainbow-delimiters-depth-5-face ((,class (:foreground ,special))))
   `(rainbow-delimiters-depth-6-face ((,class (:foreground ,type))))
   `(rainbow-delimiters-depth-7-face ((,class (:foreground ,statement))))
   `(rainbow-delimiters-depth-8-face ((,class (:foreground ,constant))))
   `(rainbow-delimiters-depth-9-face ((,class (:foreground ,storage))))
   `(rainbow-delimiters-unmatched-face ((,class (:foreground ,fg :background ,error-bg :weight bold))))

   ;; Language-specific faces corresponding to extra groups in jellybeans.vim
   `(php-variable-name ((,class (:foreground ,identifier))))
   `(php-function-name ((,class (:foreground ,function))))
   `(python-font-lock-keywords-face ((,class (:foreground ,statement))))
   `(ruby-constant-face ((,class (:foreground ,type))))
   `(ruby-symbol-face ((,class (:foreground ,ruby-symbol))))
   `(js2-function-param ((,class (:foreground ,identifier))))
   `(js2-external-variable ((,class (:foreground ,predefined))))
   `(js2-jsdoc-tag ((,class (:foreground ,structure))))
   `(web-mode-html-tag-face ((,class (:foreground ,statement))))
   `(web-mode-html-tag-bracket-face ((,class (:foreground ,statement))))
   `(web-mode-html-attr-name-face ((,class (:foreground ,identifier))))
   `(web-mode-html-attr-value-face ((,class (:foreground ,string))))
   `(web-mode-doctype-face ((,class (:foreground ,structure))))

   ;; Terminal ANSI palette derived from Jellybeans
   `(ansi-color-black ((,class (:foreground ,bg :background ,bg))))
   `(ansi-color-red ((,class (:foreground ,constant :background ,constant))))
   `(ansi-color-green ((,class (:foreground ,special :background ,special))))
   `(ansi-color-yellow ((,class (:foreground ,function :background ,function))))
   `(ansi-color-blue ((,class (:foreground ,statement :background ,statement))))
   `(ansi-color-magenta ((,class (:foreground ,identifier :background ,identifier))))
   `(ansi-color-cyan ((,class (:foreground ,structure :background ,structure))))
   `(ansi-color-white ((,class (:foreground ,fg :background ,fg))))
   `(ansi-color-bright-black ((,class (:foreground ,dim :background ,dim))))
   `(ansi-color-bright-red ((,class (:foreground ,predefined :background ,predefined))))
   `(ansi-color-bright-green ((,class (:foreground ,question :background ,question))))
   `(ansi-color-bright-yellow ((,class (:foreground ,type :background ,type))))
   `(ansi-color-bright-blue ((,class (:foreground ,ruby-control :background ,ruby-control))))
   `(ansi-color-bright-magenta ((,class (:foreground ,regexp :background ,regexp))))
   `(ansi-color-bright-cyan ((,class (:foreground ,ruby-ident :background ,ruby-ident))))
   `(ansi-color-bright-white ((,class (:foreground "#ffffff" :background "#ffffff"))))))

;; Terminal color vectors used by term/vterm-like integrations when they honor these variables.
(custom-theme-set-variables
 'jellybeans-vim
 '(ansi-color-names-vector
   ["#151515" "#cf6a4c" "#799d6a" "#fad07a"
    "#8197bf" "#c6b6ee" "#8fbfdc" "#e8e8d3"]))

(provide-theme 'jellybeans-vim)

(custom-set-faces!
  '(mode-line :background "#202328")
  '(mode-line-inactive :background "#202328"))
;;; jellybeans-vim-theme.el ends here
