hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
	hl.exec_cmd("waybar")
    hl.exec_cmd("udiskie &")
    hl.exec_cmd("hyprctl setcursor Breeze_Snow 24")
    hl.exec_cmd("/usr/lib64/hyprpolkitagent")
    hl.exec_cmd("mullvad connect")
end)
